version: '3.9'

services:

  # Database postgreSQL
  consumer-postgres-db:
    build:
      context: .
      dockerfile: /Build/Docker/Database/Dockerfile
    image: "aav13101979/i_currency-rates-postgresql-db:1.0.0"
    container_name: currency-rates-postgresql-db
    ports:
      - '5432:5432'
    volumes:
      - currency-rates-postgresql-db:/var/lib/postgresql/data
    networks:
      - appnet
    healthcheck:
      test: pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER
      start_period: 1m
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  # Eureka spring
  service-discovery-server:
    build:
      context: .
      dockerfile: Build/Docker/ServiceDiscoveryServer/Dockerfile
    image: 'aav13101979/i_service-discovery-server:1.0.0'
    container_name: service-discovery-server
    environment:
      CONTAINER_PORT: 8761
      CONTAINER_NAME: service-discovery-server
      DISCOVERY_URL: http://service-discovery-server:8761/eureka/
    ports:
      - '8761:8761'
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://service-discovery-server:8761"]
      start_period: 1m30s
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  # Gateway
  gateway:
    build:
      context: .
      dockerfile: Build/Docker/Gateway/Dockerfile
    image: 'aav13101979/i_currency-rates-gateway:1.0.0'
    container_name: currency-rates-gateway
    environment:
      DISCOVERY_URL: http://service-discovery-server:8761/eureka/
    ports:
      - '8080:8080'
    networks:
      - appnet
    links:
      - service-discovery-server
      - consumer-postgres-db
      - consumer
      - provider
      - client
      - http-client
      - nbu-service
      - monobank-service
      - privatbank-service
    depends_on:
      service-discovery-server:
        condition: service_healthy
      consumer-postgres-db:
        condition: service_healthy
      consumer:
        condition: service_healthy
      provider:
        condition: service_healthy
      client:
        condition: service_healthy
      http-client:
        condition: service_healthy
      nbu-service:
        condition: service_healthy
      monobank-service:
        condition: service_healthy
      privatbank-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://gateway:8080/actuator/health"]
      start_period: 1m
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  # Client
  client:
    build:
      context: .
      dockerfile: Build/Docker/Client/Dockerfile
    image: "aav13101979/i_currency-rates-client:1.0.0"
    container_name: currency-rates-client
    environment:
      DISCOVERY_URL: http://service-discovery-server:8761/eureka/
    ports:
      - '8081:8081'
    networks:
      - appnet
    links:
      - service-discovery-server
      - consumer-postgres-db
      - consumer
      - provider
      - http-client
      - nbu-service
      - monobank-service
      - privatbank-service
    depends_on:
      service-discovery-server:
        condition: service_healthy
      consumer-postgres-db:
        condition: service_healthy
      consumer:
        condition: service_healthy
      provider:
        condition: service_healthy
      http-client:
        condition: service_healthy
      nbu-service:
        condition: service_healthy
      monobank-service:
        condition: service_healthy
      privatbank-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://client:8081/actuator/health" ]
      start_period: 1m
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  # Consumer
  consumer:
    build:
      context: .
      dockerfile: Build/Docker/Consumer/Dockerfile
    image: "aav13101979/i_currency-rates-consumer:1.0.0"
    container_name: currency-rates-consumer
    environment:
      DISCOVERY_URL: http://service-discovery-server:8761/eureka/
    ports:
      - '8082:8082'
    networks:
      - appnet
    links:
      - service-discovery-server
      - consumer-postgres-db
      - provider
      - http-client
      - nbu-service
      - monobank-service
      - privatbank-service
    depends_on:
      service-discovery-server:
        condition: service_healthy
      consumer-postgres-db:
        condition: service_healthy
      provider:
        condition: service_healthy
      http-client:
        condition: service_healthy
      nbu-service:
        condition: service_healthy
      monobank-service:
        condition: service_healthy
      privatbank-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://consumer:8082/actuator/health" ]
      start_period: 1m
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  # Provider
  provider:
    build:
      context: .
      dockerfile: Build/Docker/Provider/Dockerfile
    image: "aav13101979/i_currency-rates-provider:1.0.0"
    container_name: currency-rates-provider
    environment:
      DISCOVERY_URL: http://service-discovery-server:8761/eureka/
    ports:
      - '8083:8083'
    networks:
      - appnet
    links:
      - service-discovery-server
      - http-client
      - nbu-service
      - privatbank-service
      - monobank-service
    depends_on:
      service-discovery-server:
        condition: service_healthy
      http-client:
        condition: service_healthy
      nbu-service:
        condition: service_healthy
      privatbank-service:
        condition: service_healthy
      monobank-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://provider:8083/actuator/health" ]
      start_period: 1m
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  # Http client
  http-client:
    build:
      context: .
      dockerfile: Build/Docker/HTTPClient/Dockerfile
    image: "aav13101979/i_http-client:1.0.0"
    container_name: http-client
    environment:
      DISCOVERY_URL: http://service-discovery-server:8761/eureka/
    ports:
      - '8087:8087'
    networks:
      - appnet
    links:
      - service-discovery-server
    depends_on:
      service-discovery-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://http-client:8087/actuator/health"]
      start_period: 1m
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  # NBU service
  nbu-service:
    build:
      context: .
      dockerfile: Build/Docker/NBU/Dockerfile
    image: "aav13101979/i_nbu-service:1.0.0"
    container_name: nbu-service
    environment:
      DISCOVERY_URL: http://service-discovery-server:8761/eureka/
    ports:
      - '8084:8084'
    networks:
      - appnet
    links:
      - service-discovery-server
      - http-client
    depends_on:
      service-discovery-server:
        condition: service_healthy
      http-client:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://nbu-service:8084/actuator/health" ]
      start_period: 1m30s
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  # Monobank service
  monobank-service:
   build:
      context: .
      dockerfile: Build/Docker/Monobank/Dockerfile
   image: "aav13101979/i_monobank-service:1.0.0"
   container_name: monobank-service
   environment:
     DISCOVERY_URL: http://service-discovery-server:8761/eureka/
   ports:
     - '8085:8085'
   networks:
     - appnet
   links:
     - service-discovery-server
     - http-client
   depends_on:
     service-discovery-server:
       condition: service_healthy
     http-client:
       condition: service_healthy
   healthcheck:
     test: [ "CMD", "curl", "-f", "http://monobank-service:8085/actuator/health" ]
     start_period: 1m30s
     interval: 5s
     timeout: 5s
     retries: 10
   restart: unless-stopped
   deploy:
     resources:
       limits:
         cpus: '0.5'
         memory: 1G

  # Privatbank service
  privatbank-service:
    build:
      context: .
      dockerfile: Build/Docker/Privatbank/Dockerfile
    image: "aav13101979/i_privarbank-service:1.0.0"
    container_name: privatbank-service
    environment:
      DISCOVERY_URL: http://service-discovery-server:8761/eureka/
    ports:
      - '8086:8086'
    networks:
      - appnet
    links:
      - service-discovery-server
      - http-client
    depends_on:
      service-discovery-server:
        condition: service_healthy
      http-client:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://privatbank-service:8086/actuator/health" ]
      start_period: 1m30s
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  # PGAdmin
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "13101979@ukr.net"
      PGADMIN_DEFAULT_PASSWORD: "aav13101979"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - appnet

networks:
  appnet:

volumes:
  currency-rates-postgresql-db:
  pgadmin-data: