# Port
server:
  port: 8085

# App
spring:
  application:
    name: MONOBANK-SERVICE
  cloud:
    config:
      enabled: false

# Eureka client
eureka:
  instance:
    hostname: eureka-client
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${CONTAINER_NAME}:8761/eureka

