# Port
server:
  port: 8761

# App
spring:
  application:
    name: service-discovery-server

# Eureka server
eureka:
  server:
    enable-self-preservation: false
  client:
    healthcheck:
      enabled: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port:8761}/eureka