# Port
server:
  port: 8082

# App
spring:
  application:
    name: currency-rates-consumer
  cloud:
    config:
      enabled: false
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    url: ${PATH_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ${DB_SCHEMAS}
  flyway:
    enabled: true
    schemas: ${DB_SCHEMAS}
    validate-on-migrate: true
    locations: classpath:db/migration

# Eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka}

scheduler:
  cron: '0 0,5,10,15,20,25,30,35,40,45,50,55 * * * *'