spring:
  profiles:
    default: ${PROFILE}
  application:
    name: currency-rates-consumer
  cloud:
    config:
      enabled: false
  task:
    scheduling:
      pool:
        size: 1000
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka}

scheduler:
  cron: '0 0,5,10,15,20,25,30,35,40,45,50,55 * * * *'