server:
  port: 8082

spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    url: ${PATH_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ${DB_SCHEMAS}
  flyway:
    enabled: true
    schemas: ${DB_SCHEMAS}
    validate-on-migrate: true
    locations: classpath:db/migration