# Port
server:
  port: 8761

# App
spring:
  application:
    name: SERVICE_DISCOVERY_SERVER

# Eureka server
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: service-discovery-server
    status-page-url: https://localhost:8761/info
    health-check-url: https://localhost:8761/health
    home-page-url: https://$localhost:8761
  client:
    healthcheck:
      enabled: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


      eureka:
      instance:
      statusPageUrl:
      healthCheckUrl:
      homePageUrl: /

