# Port
server:
  port: 8080

# App
spring:
  application:
    name: CURRENCY-RATES-CLIENT
  cloud:
    config:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${PATH_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: your-password

# Eureka client
eureka:
  instance:
    hostname: eureka-client
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${CONTAINER_NAME}:8761/eureka
