name: CurrencyRates with Maven. CI/CD.

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, edited, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Access to repository.
        uses: actions/checkout@v4
      - name: Set up JDK 19.
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'oracle'
          cash: maven
      - name: Build HTTPClient and run tests.
        run: mvn -B package --file HTTPClient/pom.xml
      - name: Copy HTTPClient jar file
        run: mkdir package && cp HTTPClient/target/*.jar package
      - name: Upload Artifacts for all modules.
        uses: actions/upload-artifact@v3
        with:
          path: package
          name: jar-files
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts for all modules.
        uses: actions/download-artifact@v3
        with:
          path: target
          name: jar-files