name: CurrencyRates with Maven. CI/CD.

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/*'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/*'
    types:
      - opened
      - edited
      - reopened

env:
  JAVA: '19'
  DISTRIBUTION: 'oracle'
  ARCHITECTURE: x64

  CURRENCY_RATES_GATEWAY_PATH: ./CurrencyRatesServices/UtilityServices/CurrencyRatesGateway/
  SERVICE_DISCOVERY_SERVER_PATH: ./CurrencyRatesServices/UtilityServices/ServiceDiscoveryServer/
  HTTPCLIENT_PATH: ./CurrencyRatesServices/ApplicationServices/HTTPClient/
  PRIVATBANK_SERVICE_PATH: ./CurrencyRatesServices/ApplicationServices/PrivatbankService/
  MONOBANK_SERVICE_PATH: ./CurrencyRatesServices/ApplicationServices/MonobankService/
  NBU_SERVICE_PATH: ./CurrencyRatesServices/ApplicationServices/NBUService/
  CURRENCY_RATES_PROVIDER_PATH: ./CurrencyRatesServices/ApplicationServices/CurrencyRatesProvider/
  CURRENCY_RATES_CONSUMER_PATH: ./CurrencyRatesServices/ApplicationServices/CurrencyRatesConsumer/
  CURRENCY_RATES_CLIENT_PATH: ./CurrencyRatesServices/ApplicationServices/CurrencyRatesClient/

  CURRENCY_RATES_EXCEPTION_HANDLER_PATH : ./ExceptionHandler/
  CURRENCY_RATES_HELPERS_PATH : ./CurrencyRatesLibraries/Helpers/
  CURRENCY_RATES_DTO_PATH : ./CurrencyRatesLibraries/DTO/
  CURRENCY_RATES_DAO_PATH : ./CurrencyRatesLibraries/DAO/
  CURRENCY_RATES_ENUMERATORS_PATH : ./CurrencyRatesLibraries/Enumerators/
  CURRENCY_RATES_INTERFACES_PATH : ./CurrencyRatesLibraries/Interfaces/
  CURRENCY_RATES_REPOSITORY_PATH : ./CurrencyRatesLibraries/Repository/

  CURRENCY_RATES_EXCEPTION_HANDLER_FILENAME : exceptionhandler-1.0.0.jar
  CURRENCY_RATES_HELPERS_FILENAME : helpers-1.0.0.jar
  CURRENCY_RATES_DTO_FILENAME : dto-1.0.0.jar
  CURRENCY_RATES_DAO_FILENAME : dao-1.0.0.jar
  CURRENCY_RATES_ENUMERATORS_FILENAME : enumerators-1.0.0.jar
  CURRENCY_RATES_INTERFACES_FILENAME : interfaces-1.0.0.jar
  CURRENCY_RATES_REPOSITORY_FILENAME : repository-1.0.0.jar

jobs:

  clean-and-package-currency-rates-app:
    runs-on: ubuntu-latest
    steps:
      - name: Copy project from repository
        uses: actions/checkout@v4
      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA }}
          distribution: ${{ env.DISTRIBUTION }}
          architecture: ${{ env.ARCHITECTURE }}
          cache: maven
      - name: Clean and package project and run tests
        run: mvn clean package --file ./pom.xml
      - name: Copy jar file
        run: mkdir package &&
          cp ${{ env.CURRENCY_RATES_EXCEPTION_HANDLER_PATH }}target/${{ env.CURRENCY_RATES_EXCEPTION_HANDLER_FILENAME }} package &&
          cp ${{ env.CURRENCY_RATES_HELPERS_PATH }}target/${{ env.CURRENCY_RATES_HELPERS_FILENAME }} package &&
          cp ${{ env.CURRENCY_RATES_DTO_PATH }}target/${{ env.CURRENCY_RATES_DTO_FILENAME }} package &&
          cp ${{ env.CURRENCY_RATES_DAO_PATH }}target/${{ env.CURRENCY_RATES_DAO_FILENAME }} package &&
          cp ${{ env.CURRENCY_RATES_ENUMERATORS_PATH }}target/${{ env.CURRENCY_RATES_ENUMERATORS_FILENAME }} package &&
          cp ${{ env.CURRENCY_RATES_INTERFACES_PATH }}target/${{ env.CURRENCY_RATES_INTERFACES_FILENAME }} package &&
          cp ${{ env.CURRENCY_RATES_REPOSITORY_PATH }}target/${{ env.CURRENCY_RATES_REPOSITORY_FILENAME }} package &&
          cp ${{ env.CURRENCY_RATES_GATEWAY_PATH }}target/*.jar package &&
          cp ${{ env.SERVICE_DISCOVERY_SERVER_PATH }}target/*.jar package &&
          cp ${{ env.HTTPCLIENT_PATH }}target/*.jar package &&
          cp ${{ env.PRIVATBANK_SERVICE_PATH }}target/*.jar package &&
          cp ${{ env.MONOBANK_SERVICE_PATH }}target/*.jar package &&
          cp ${{ env.NBU_SERVICE_PATH }}target/*.jar package &&
          cp ${{ env.CURRENCY_RATES_PROVIDER_PATH }}target/*.jar package &&
          cp ${{ env.CURRENCY_RATES_CONSUMER_PATH }}target/*.jar package &&
          cp ${{ env.CURRENCY_RATES_CLIENT_PATH }}target/*.jar package &&
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: package
          name: artifacts
          retention-days: 1

  deploy_currency_rates:
    needs:
      - clean-and-package-currency-rates-app
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts for all modules.
        uses: actions/download-artifact@v3
        with:
          path: package
          name: artifacts